.TH "Headers/FileOperations Directory Reference" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/FileOperations Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFileReader\&.hpp\fP"
.br
.RI "Class for reading project related files\&. "
.ti -1c
.RI "file \fBFileSalvor\&.hpp\fP"
.br
.RI "Class for missing data calculation and recovery\&. "
.ti -1c
.RI "file \fBRowParser\&.hpp\fP"
.br
.RI "Class for parsing rows of the data file\&. "
.in -1c
