.TH "Headers Directory Reference" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFileOperations\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMatrixOps\&.hpp\fP"
.br
.RI "Header for operations with the data matrices\&. "
.ti -1c
.RI "file \fBRadixSort\&.hpp\fP"
.br
.RI "Header for implementation of Radix Sort with floating point numbers\&. "
.ti -1c
.RI "file \fBSimiCalc\&.hpp\fP"
.br
.RI "Class for similitude calculation between two matrices\&. "
.ti -1c
.RI "file \fBTUIController\&.hpp\fP"
.br
.RI "Header for TUI (Terminal User Interface) functions\&. "
.in -1c
