.TH "convData" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
convData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RadixSort\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBglobalExp\fP"
.br
.ti -1c
.RI "std::vector< int > \fBdata\fP"
.br
.ti -1c
.RI "int \fBglobalMult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic struct to hold the converted floating point array and its rounding exponent 
.SH "Member Data Documentation"
.PP 
.SS "std::vector< int > convData::data"
The biggest exponent of the array 
.SS "int convData::globalExp"

.SS "int convData::globalMult"


.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
