.TH "Source/FileReaderSrc.cpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/FileReaderSrc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Headers/FileOperations/FileReader\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
