.TH "Headers/FileOperations/FileSalvor.hpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/FileOperations/FileSalvor.hpp \- Class for missing data calculation and recovery\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include '\&.\&./MatrixOps\&.hpp'\fP
.br
\fR#include '\&.\&./RadixSort\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileSalvor\fP"
.br
.RI "Main class\&. "
.ti -1c
.RI "class \fBFileSalvorNR\fP"
.br
.RI "No data change logging\&. "
.ti -1c
.RI "class \fBFileSalvorWR\fP"
.br
.RI "w/Data Change logging "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILESALVOR_HPP_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for missing data calculation and recovery\&. 


.PP
\fBAuthor\fP
.RS 4
Victor Aguilar Rodriguez (ar202341753@alm.buap.mx) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-10-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBFileSalvor\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILESALVOR_HPP_"

.PP
Definition at line \fB22\fP of file \fBFileSalvor\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
