.TH "Headers/FileOperations/FileReader.hpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/FileOperations/FileReader.hpp \- Class for reading project related files\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileReader\fP"
.br
.RI "Main class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for reading project related files\&. 


.PP
\fBAuthor\fP
.RS 4
Victor Aguilar Rodriguez (ar202341753@alm.buap.mx) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-10-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBFileReader\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
