.TH "FileReader" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileReader \- Main class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FileReader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileReader\fP ()"
.br
.ti -1c
.RI "\fB~FileReader\fP ()"
.br
.ti -1c
.RI "void \fBsetInputFile\fP (std::string)"
.br
.RI "Sets the input file for the \fBFileReader\fP\&. "
.ti -1c
.RI "std::vector< std::string > \fBgetLines\fP ()"
.br
.RI "Gets all the rows from the input file as a string and outputs it as an array\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileReader::FileReader ()"

.SS "FileReader::~FileReader ()"

.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > FileReader::getLines ()"

.PP
Gets all the rows from the input file as a string and outputs it as an array\&. 
.PP
\fBReturns\fP
.RS 4
the array of rows 
.RE
.PP

.SS "void FileReader::setInputFile (std::string file)"

.PP
Sets the input file for the \fBFileReader\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP the input file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
