.TH "Source/FileSalvorSrc.cpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/FileSalvorSrc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Headers/FileOperations/FileSalvor\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBtruncate\fP (int n_places, double num)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double truncate (int n_places, double num)\fR [inline]\fP"
truncates a double value to n places 
.PP
\fBParameters\fP
.RS 4
\fIn_places\fP The number of decimal digits to truncate to 
.br
\fInum\fP The number to truncate
.RE
.PP
\fBReturns\fP
.RS 4
the truncated value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
