.TH "MatrixData" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatrixData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MatrixOps\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdataSize\fP"
.br
.ti -1c
.RI "int \fBframeSize\fP"
.br
.ti -1c
.RI "std::string \fBfileName\fP"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBMatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct to hold the data from the parsed matrix 
.SH "Member Data Documentation"
.PP 
.SS "int MatrixData::dataSize"

.SS "std::string MatrixData::fileName"
Size of the rows (Data Frame) 
.SS "int MatrixData::frameSize"
Size of the matrix as rows 
.SS "std::vector<std::vector<double> > MatrixData::Matrix"
Input filename 

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
