.TH "Headers/FileOperations/RowParser.hpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/FileOperations/RowParser.hpp \- Class for parsing rows of the data file\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRowParser\fP"
.br
.RI "Main Class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for parsing rows of the data file\&. 


.PP
\fBAuthor\fP
.RS 4
Victor Aguilar Rodriguez (ar202341753@alm.buap.mx) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-10-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBRowParser\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
