.TH "SimilCalcBayesian::ProbabilityData" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilCalcBayesian::ProbabilityData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimiCalc\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "double \fBprob\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int SimilCalcBayesian::ProbabilityData::idx"

.SS "double SimilCalcBayesian::ProbabilityData::prob"
Index of the row 

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
