.TH "SimilCalcAbs::diffData" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilCalcAbs::diffData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimiCalc\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "double \fBdiff\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double SimilCalcAbs::diffData::diff"

.SS "int SimilCalcAbs::diffData::idx"


.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
