.TH "SimilCalc" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilCalc
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimiCalc\&.hpp>\fP
.PP
Inherited by \fBSimilCalcAbs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdiffCalc\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class 
.SH "Member Function Documentation"
.PP 
.SS "virtual void SimilCalc::diffCalc ()\fR [pure virtual]\fP"

.PP
Implemented in \fBSimilCalcAbs\fP, and \fBSimilCalcBayesian\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
