.TH "Headers/SimiCalc.hpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/SimiCalc.hpp \- Class for similitude calculation between two matrices\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimilCalc\fP"
.br
.ti -1c
.RI "class \fBSimilCalcAbs\fP"
.br
.ti -1c
.RI "struct \fBSimilCalcAbs::diffData\fP"
.br
.ti -1c
.RI "class \fBSimilCalcBayesian\fP"
.br
.ti -1c
.RI "struct \fBSimilCalcBayesian::ProbabilityData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for similitude calculation between two matrices\&. 


.PP
\fBAuthor\fP
.RS 4
Victor Aguilar Rodriguez (ar202341753@alm.buap.mx) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-10-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBSimiCalc\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
