.TH "Source/SimilCalcSrc.cpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/SimilCalcSrc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Headers/SimiCalc\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTWOPISQRT\fP   sqrt(M_PI*2)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBCalculateVariance\fP (std::vector< std::vector< double > > &Matrix, std::vector< std::vector< double > > Means, int col, int id)"
.br
.ti -1c
.RI "double \fBCalculateProb\fP (std::vector< std::vector< double > > &Matrix, std::vector< std::vector< double > > Means, int col, int id)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TWOPISQRT   sqrt(M_PI*2)"

.SH "Function Documentation"
.PP 
.SS "double CalculateProb (std::vector< std::vector< double > > & Matrix, std::vector< std::vector< double > > Means, int col, int id)"

.SS "double CalculateVariance (std::vector< std::vector< double > > & Matrix, std::vector< std::vector< double > > Means, int col, int id)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
