.TH "testArea/sortTest.cpp" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testArea/sortTest.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconvData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdtoi\fP (double n)"
.br
.ti -1c
.RI "int \fBgetMax\fP (std::vector< int > arr)"
.br
.ti -1c
.RI "\fBconvData\fP \fBdvtoiv\fP (std::vector< double > vct)"
.br
.ti -1c
.RI "void \fBcountSrt\fP (std::vector< int > &arr, int exp)"
.br
.ti -1c
.RI "void \fBRadixSrt\fP (std::vector< int > &vct)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void countSrt (std::vector< int > & arr, int exp)"

.SS "int dtoi (double n)"

.SS "\fBconvData\fP dvtoiv (std::vector< double > vct)"

.SS "int getMax (std::vector< int > arr)"

.SS "int main ()"

.SS "void RadixSrt (std::vector< int > & vct)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
