.TH "TerminalSize" 3 "Version Final" "Final Programming Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TerminalSize
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TUIController\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int TerminalSize::columns"

.SS "int TerminalSize::rows"


.SH "Author"
.PP 
Generated automatically by Doxygen for Final Programming Project from the source code\&.
